### ISSUE TITLE
architect 6.x docs master issue

### ISSUE THREAD

**Issue by brianleroux** [architect/arc.codes#114]
WIP on `v4` branch deploying here https://arc.begin.com

- [x] write runtime `arc.tables`
- [x] finish `/guides/testing`
- [x] write `/guides/upgrade`
- [x] restore https://arc.begin.com/reference/functions/http/node/classic
- [x] restore https://arc.begin.com/reference/functions/http/node/proxy
- [x] restore https://arc.begin.com/reference/functions/http/node/middleware
- [x] restore https://arc.begin.com/reference/functions/http/node/helpers
- [x] restore https://arc.begin.com/reference/functions/http/node/classic
- [x] add notes about AWS SAM to `/quickstart`
- [x] switch syntax highlighting to something more neon cyber punk and inc ruby/python
- [x] finish `/primitives/websockets`
- [x] finish `/primitives/events`
- [x] finish `/primitives/queues`
- [x] finish `/primitives/tables`
- [x] left nav expland/collapse carat
- [x] review `/reference/cli/*`
- [x] review `/reference/cli/.arc`
- [x] review `/reference/cli/.arc-config`
- [x] review `/reference/cli/.arc-env`
- [x] review `/reference/functions`

**Comment by mikemaccana** [comment]
Quick one for the review: it'd be good to use `request` consistently in the examples. Generally acronyms should be avoided in docs. `http` uses `request`, but there's still some `req` around. Happy to do this.

**Comment by brianleroux** [comment]
Yea think a deliberate style choice is good. The 'official' AWS moniker is `event` and does show up as a named param in Ruby and Python. so you end up doing `event[:request]` and stuff like that. 

Mostly choose `req` because its pretty standard throughout node `http.createServer((req, res)` and the Express ecosystem but that makes less and less sense as we add runtimes.

**Comment by brianleroux** [comment]
ok this isn't DONE but its a good first pass and moving over to other stuff
